[tool.poetry]
name = "property-graph-lab"
version = "0.1.0"
description = ""
authors = ["Marek Hradil <marecek@marekhradil.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
